/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-08-22 08:37:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpServletRequest;

public final class benvenuto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("javax.servlet.http.HttpServletRequest");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"it\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    \r\n");
      out.write("var isUserLoggedIn = ");
      out.print(request.getAttribute("login"));
      out.write(";\r\n");
      out.write("\r\n");
      out.write("if (!isUserLoggedIn || isUserLoggedIn == null) {\r\n");
      out.write("    // L'utente non è autenticato, reindirizzalo alla pagina di login\r\n");
      out.write("    window.location.href = \"userNotLoggedLogin.jsp\";\r\n");
      out.write("} \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>HomePage - Proposte progettuali</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Arial, sans-serif;\r\n");
      out.write("\tbackground-color: #f4f4f4;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tmax-width: 400px;\r\n");
      out.write("\tmargin: 50px auto;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbox-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table td {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 8px;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"] {\r\n");
      out.write("\tbackground-color: #4caf50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"]:hover {\r\n");
      out.write("\tbackground-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("tr.logout-row {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"button\"].logout-button {\r\n");
      out.write("\tbackground-color: red;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"] {\r\n");
      out.write("\tbackground-color: #4caf50;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contenutoBanner {\r\n");
      out.write("\tbackground-color: #f9f9f9; /* Colore sfondo del banner */\r\n");
      out.write("\tborder: 1px solid #ddd; /* Bordo del banner */\r\n");
      out.write("\tborder-radius: 5px; /* Angoli arrotondati */\r\n");
      out.write("\tpadding: 10px; /* Spaziatura interna */\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#listaProposteBanner {\r\n");
      out.write("\tbackground-color: #fff; /* Colore sfondo del banner */\r\n");
      out.write("\tborder: 1px solid #ddd; /* Bordo del banner */\r\n");
      out.write("\tborder-radius: 5px; /* Angoli arrotondati */\r\n");
      out.write("\tpadding: 10px; /* Spaziatura interna */\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\ttext-align: center; /* Aggiunto lo stile per centrare il contenuto */\r\n");
      out.write("\t    list-style-type: none; /* Rimuovi i pallini dalla lista */\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction uploadFile() {\r\n");
      out.write("\t\tvar formData = new FormData(document.getElementById('uploadForm'));\r\n");
      out.write("\r\n");
      out.write("\t\t$\r\n");
      out.write("\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\turl : 'PropostaServlet',\r\n");
      out.write("\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\tdata : formData,\r\n");
      out.write("\t\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t// Aggiorna il contenuto del banner con il risultato della risposta AJAX\r\n");
      out.write("\t\t\t\t\t\t$('#contenutoBanner').html(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(xhr, status, error) {\r\n");
      out.write("\t\t\t\t\t\tconsole.error(\r\n");
      out.write("\t\t\t\t\t\t\t\t'Errore durante il caricamento del file:',\r\n");
      out.write("\t\t\t\t\t\t\t\tstatus, error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// Chiamata AJAX separata per caricare la lista delle proposte quando la pagina si carica\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tcaricaListaProposte();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("var scrittaAggiunta = false;\r\n");
      out.write("\r\n");
      out.write("var isLogoutExecuted = false;\r\n");
      out.write("var isRefreshing = false;\r\n");
      out.write("var isProposteLoading = false;\r\n");
      out.write("\r\n");
      out.write("// Funzione per caricare la lista delle proposte\r\n");
      out.write("function caricaListaProposte() {\r\n");
      out.write("    isProposteLoading = true;\r\n");
      out.write("\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: 'PropostaServlet',\r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        dataType: 'json',\r\n");
      out.write("        success: function (data) {\r\n");
      out.write("            // Aggiorna la lista delle proposte nel banner\r\n");
      out.write("            var listaProposte = $('#listaProposteBanner');\r\n");
      out.write("            listaProposte.empty();\r\n");
      out.write("\r\n");
      out.write("            // Aggiungo la scritta solo se non è stata ancora aggiunta\r\n");
      out.write("            if (!scrittaAggiunta) {\r\n");
      out.write("                listaProposte.append('<p><strong>Lista proposte progettuali</strong></p>');\r\n");
      out.write("                scrittaAggiunta = true; // Imposta la variabile a true dopo l'aggiunta\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Itera sulla lista delle proposte\r\n");
      out.write("            $.each(data, function (index, proposta) {\r\n");
      out.write("                // Utilizza un link anziché un paragrafo e aggiungi una classe per lo stile e l'interattività\r\n");
      out.write("                var link = $('<a>', {\r\n");
      out.write("                    class: 'file-link',\r\n");
      out.write("                    href: '#',\r\n");
      out.write("                    'data-nomefile': proposta.nomeFile,\r\n");
      out.write("                    'data-nomeutente': proposta.username,\r\n");
      out.write("                    'data-html': proposta.contenutoHtml,\r\n");
      out.write("                    text: 'Username: ' + proposta.username + ', Proposta: ' + proposta.nomeFile\r\n");
      out.write("                });\r\n");
      out.write("                listaProposte.append($('<li>').append(link));\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            // Aggiungo uno script jQuery per gestire il clic sul link del file\r\n");
      out.write("            $('.file-link').on('click', function (event) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                var nomeFile = $(this).data('nomefile');\r\n");
      out.write("                var nomeUtente = $(this).data('nomeutente');\r\n");
      out.write("                var contenutoHtml = $(this).data('html');\r\n");
      out.write("\r\n");
      out.write("                // Creazione del messaggio in grassetto\r\n");
      out.write("                var messaggio = \"Stai visualizzando la proposta progettuale <strong>\" + nomeFile + \"</strong> di <strong>\" + nomeUtente + \"</strong>\";\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                // Visualizza il messaggio HTML nel banner\r\n");
      out.write("                $('#contenutoBanner').html('<p>' + messaggio + '</p>' + contenutoHtml);\r\n");
      out.write("            });\r\n");
      out.write("            isProposteLoading = false;\r\n");
      out.write("\r\n");
      out.write("        },\r\n");
      out.write("        error: function (xhr, status, error) {\r\n");
      out.write("            console.error(\r\n");
      out.write("                'Errore durante il recupero della lista delle proposte:',\r\n");
      out.write("                status, error);\r\n");
      out.write("           \t\tisProposteLoading = false;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var isLogoutExecuted = false;\r\n");
      out.write("var isRefreshing = false;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function logout() {\r\n");
      out.write("    if (!isLogoutExecuted) {\r\n");
      out.write("        // Effettua una chiamata al server per invalidare la sessione\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'LogoutServlet',\r\n");
      out.write("            type: 'GET',\r\n");
      out.write("            success: function () {\r\n");
      out.write("                $('#listaProposteBanner').empty();\r\n");
      out.write("                localStorage.removeItem('nomeUtente');\r\n");
      out.write("\r\n");
      out.write("                // Reindirizza alla pagina di login dopo il logout\r\n");
      out.write("                window.location.href = \"userNotLoggedLogin.jsp\";\r\n");
      out.write("            },\r\n");
      out.write("            error: function (xhr, status, error) {\r\n");
      out.write("                console.error('Errore durante il logout:', status, error);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        isLogoutExecuted = true;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//Gestisci il logout quando l'utente sta lasciando la pagina\r\n");
      out.write("\r\n");
      out.write("window.addEventListener('beforeunload', function (event) {\r\n");
      out.write("    isRefreshing = true;\r\n");
      out.write("\r\n");
      out.write("    console.log('beforeunload event');\r\n");
      out.write("\r\n");
      out.write("    if (!event.persisted && !isLogoutExecuted && !isRefreshing && !isProposteLoading) {\r\n");
      out.write("        // Esegui la funzione di logout solo se necessario e non è un aggiornamento della pagina\r\n");
      out.write("                console.log('Performing logout');\r\n");
      out.write("\r\n");
      out.write("        logout();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// Gestisci il logout quando l'utente fa clic sul pulsante di navigazione del browser\r\n");
      out.write("window.addEventListener('popstate', function () {\r\n");
      out.write("    console.log('popstate event');\r\n");
      out.write("\r\n");
      out.write("    if (!isLogoutExecuted && !isRefreshing) {\r\n");
      out.write("        // Esegui la funzione di logout solo se necessario\r\n");
      out.write("                console.log('Performing logout');\r\n");
      out.write("\r\n");
      out.write("        logout();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("      var inattivitaTimer; // Variabile per memorizzare l'ID del timer\r\n");
      out.write("\r\n");
      out.write("    // Funzione chiamata quando l'utente compie un'azione\r\n");
      out.write("    function resetInattivitaTimer() {\r\n");
      out.write("        clearTimeout(inattivitaTimer); // Resetta il timer\r\n");
      out.write("        inattivitaTimer = setTimeout(function() {\r\n");
      out.write("            // Esegui la funzione di logout dopo il periodo di inattività\r\n");
      out.write("            logout();\r\n");
      out.write("        }, 600000); // 10minuti\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Chiamata quando la pagina si carica\r\n");
      out.write("    $(document).on('click keypress mousemove', function() {\r\n");
      out.write("        resetInattivitaTimer();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function checkAuthentication() {\r\n");
      out.write("    var nomeUtente = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nomeUtente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; // Ottieni il valore dalla JSP\r\n");
      out.write("    console.log(\"Nome utente:\", nomeUtente); // Aggiungi questa riga per stampare nella console\r\n");
      out.write("\r\n");
      out.write("    if (!nomeUtente || nomeUtente.trim() === \"\") {\r\n");
      out.write("        window.location.href = \"userNotLoggedLogin.jsp\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Chiamata alla funzione durante il caricamento della pagina\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("    checkAuthentication();\r\n");
      out.write("    caricaListaProposte(); // Aggiunta la chiamata alla funzione caricaListaProposte\r\n");
      out.write("    \r\n");
      out.write("    // Quando la pagina è completamente caricata\r\n");
      out.write("    var contenutoBanner = $('#contenutoBanner');\r\n");
      out.write("    if (contenutoBanner.is(':empty')) {\r\n");
      out.write("        contenutoBanner.html('<p>Non stai visualizzando nessuna proposta</p>');\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Form di caricamento proposta -->\r\n");
      out.write("\t<form id=\"uploadForm\" method=\"post\" action=\"javascript:void(0);\"\r\n");
      out.write("\t\tenctype=\"multipart/form-data\" onsubmit=\"uploadFile()\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"nomeUtente\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nomeUtente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<h1>Benvenuto, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nomeUtente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("!</h1>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Carica proposta progettuale</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"file\" name=\"Proposta progettuale\"\r\n");
      out.write("\t\t\t\t\tautocomplete=\"off\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td><small>Il file deve essere di formato .txt e pesare\r\n");
      out.write("\t\t\t\t\t\tmassimo 20 MB.</small></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"button\" class=\"logout-button\" value=\"Logout\"\r\n");
      out.write("\t\t\t\t\tonclick=\"logout()\"></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" value=\"Carica Proposta\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<!-- Banner -->\r\n");
      out.write("\t\t\t\t<!--<div id=\"banner\">-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div id=\"contenutoBanner\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(request.getAttribute("contenutoFiltrato"));
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"listaProposteBanner\"></div>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
