/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-08-22 08:37:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userLoggedIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/css/styleIndexLogged.css", Long.valueOf(1705341368684L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Homepage Web Application</title>\r\n");
      out.write("    \r\n");
      out.write(" <style>\r\n");
      out.write(" ");
      out.write("@charset \"ISO-8859-1\";\r\n");
      out.write("body {\r\n");
      out.write("    font-family: sans-serif;\r\n");
      out.write("    background-color: #ececff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background-color: #8ac1ff;\r\n");
      out.write("    border:1px solid #001328;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar h1 {\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-buttons {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-image {\r\n");
      out.write("    width: 50px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("    min-width: 160px;\r\n");
      out.write("    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("    padding: 12px 16px;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    text-align: left; /* Aggiunto per allineare il testo a sinistra */\r\n");
      out.write("    padding:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("    display: block; /* Aggiunto per far apparire i link uno sotto l'altro */\r\n");
      out.write("    margin-bottom:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border: 1px solid black;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    max-width: 80vw;\r\n");
      out.write("    padding: 5vw;\r\n");
      out.write("    background-color: #8ac1ff;\r\n");
      out.write("    opacity: 0.9;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    border:1px solid #001328;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%, -50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" </style>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction uploadFile() {\r\n");
      out.write("\t\tvar formData = new FormData(document.getElementById('uploadForm'));\r\n");
      out.write("\r\n");
      out.write("\t\t$\r\n");
      out.write("\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\turl : 'PropostaServlet',\r\n");
      out.write("\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\tdata : formData,\r\n");
      out.write("\t\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t// Aggiorna il contenuto del banner con il risultato della risposta AJAX\r\n");
      out.write("\t\t\t\t\t\t$('#contenutoBanner').html(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(xhr, status, error) {\r\n");
      out.write("\t\t\t\t\t\tconsole.error(\r\n");
      out.write("\t\t\t\t\t\t\t\t'Errore durante il caricamento del file:',\r\n");
      out.write("\t\t\t\t\t\t\t\tstatus, error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// Chiamata AJAX separata per caricare la lista delle proposte quando la pagina si carica\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tcaricaListaProposte();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("var scrittaAggiunta = false;\r\n");
      out.write("\r\n");
      out.write("var isLogoutExecuted = false;\r\n");
      out.write("var isRefreshing = false;\r\n");
      out.write("var isProposteLoading = false;\r\n");
      out.write("\r\n");
      out.write("// Funzione per caricare la lista delle proposte\r\n");
      out.write("function caricaListaProposte() {\r\n");
      out.write("    isProposteLoading = true;\r\n");
      out.write("\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: 'PropostaServlet',\r\n");
      out.write("        type: 'GET',\r\n");
      out.write("        dataType: 'json',\r\n");
      out.write("        success: function (data) {\r\n");
      out.write("            // Aggiorna la lista delle proposte nel banner\r\n");
      out.write("            var listaProposte = $('#listaProposteBanner');\r\n");
      out.write("            listaProposte.empty();\r\n");
      out.write("\r\n");
      out.write("            // Aggiungo la scritta solo se non è stata ancora aggiunta\r\n");
      out.write("            if (!scrittaAggiunta) {\r\n");
      out.write("                listaProposte.append('<p><strong>Lista proposte progettuali</strong></p>');\r\n");
      out.write("                scrittaAggiunta = true; // Imposta la variabile a true dopo l'aggiunta\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Itera sulla lista delle proposte\r\n");
      out.write("            $.each(data, function (index, proposta) {\r\n");
      out.write("                // Utilizza un link anziché un paragrafo e aggiungi una classe per lo stile e l'interattività\r\n");
      out.write("                var link = $('<a>', {\r\n");
      out.write("                    class: 'file-link',\r\n");
      out.write("                    href: '#',\r\n");
      out.write("                    'data-nomefile': proposta.nomeFile,\r\n");
      out.write("                    'data-nomeutente': proposta.username,\r\n");
      out.write("                    'data-html': proposta.contenutoHtml,\r\n");
      out.write("                    text: 'Username: ' + proposta.username + ', Proposta: ' + proposta.nomeFile\r\n");
      out.write("                });\r\n");
      out.write("                listaProposte.append($('<li>').append(link));\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            // Aggiungo uno script jQuery per gestire il clic sul link del file\r\n");
      out.write("            $('.file-link').on('click', function (event) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                var nomeFile = $(this).data('nomefile');\r\n");
      out.write("                var nomeUtente = $(this).data('nomeutente');\r\n");
      out.write("                var contenutoHtml = $(this).data('html');\r\n");
      out.write("\r\n");
      out.write("                // Creazione del messaggio in grassetto\r\n");
      out.write("                var messaggio = \"Stai visualizzando la proposta progettuale <strong>\" + nomeFile + \"</strong> di <strong>\" + nomeUtente + \"</strong>\";\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                // Visualizza il messaggio HTML nel banner\r\n");
      out.write("                $('#contenutoBanner').html('<p>' + messaggio + '</p>' + contenutoHtml);\r\n");
      out.write("            });\r\n");
      out.write("            isProposteLoading = false;\r\n");
      out.write("\r\n");
      out.write("        },\r\n");
      out.write("        error: function (xhr, status, error) {\r\n");
      out.write("            console.error(\r\n");
      out.write("                'Errore durante il recupero della lista delle proposte:',\r\n");
      out.write("                status, error);\r\n");
      out.write("           \t\tisProposteLoading = false;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var isLogoutExecuted = false;\r\n");
      out.write("var isRefreshing = false;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function logout() {\r\n");
      out.write("    if (!isLogoutExecuted) {\r\n");
      out.write("        // Effettua una chiamata al server per invalidare la sessione\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'LogoutServlet',\r\n");
      out.write("            type: 'GET',\r\n");
      out.write("            success: function () {\r\n");
      out.write("                $('#listaProposteBanner').empty();\r\n");
      out.write("                localStorage.removeItem('nomeUtente');\r\n");
      out.write("\r\n");
      out.write("                // Reindirizza alla pagina di login dopo il logout\r\n");
      out.write("                window.location.href = \"userNotLoggedLogin.jsp\";\r\n");
      out.write("            },\r\n");
      out.write("            error: function (xhr, status, error) {\r\n");
      out.write("                console.error('Errore durante il logout:', status, error);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        isLogoutExecuted = true;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//Gestisci il logout quando l'utente sta lasciando la pagina\r\n");
      out.write("\r\n");
      out.write("window.addEventListener('beforeunload', function (event) {\r\n");
      out.write("    isRefreshing = true;\r\n");
      out.write("\r\n");
      out.write("    console.log('beforeunload event');\r\n");
      out.write("\r\n");
      out.write("    if (!event.persisted && !isLogoutExecuted && !isRefreshing && !isProposteLoading) {\r\n");
      out.write("        // Esegui la funzione di logout solo se necessario e non è un aggiornamento della pagina\r\n");
      out.write("                console.log('Performing logout');\r\n");
      out.write("\r\n");
      out.write("        logout();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// Gestisci il logout quando l'utente fa clic sul pulsante di navigazione del browser\r\n");
      out.write("window.addEventListener('popstate', function () {\r\n");
      out.write("    console.log('popstate event');\r\n");
      out.write("\r\n");
      out.write("    if (!isLogoutExecuted && !isRefreshing) {\r\n");
      out.write("        // Esegui la funzione di logout solo se necessario\r\n");
      out.write("                console.log('Performing logout');\r\n");
      out.write("\r\n");
      out.write("        logout();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("      var inattivitaTimer; // Variabile per memorizzare l'ID del timer\r\n");
      out.write("\r\n");
      out.write("    // Funzione chiamata quando l'utente compie un'azione\r\n");
      out.write("    function resetInattivitaTimer() {\r\n");
      out.write("        clearTimeout(inattivitaTimer); // Resetta il timer\r\n");
      out.write("        inattivitaTimer = setTimeout(function() {\r\n");
      out.write("            // Esegui la funzione di logout dopo il periodo di inattività\r\n");
      out.write("            logout();\r\n");
      out.write("        }, 600000); // 10minuti\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Chiamata quando la pagina si carica\r\n");
      out.write("    $(document).on('click keypress mousemove', function() {\r\n");
      out.write("        resetInattivitaTimer();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function checkAuthentication() {\r\n");
      out.write("    var nomeUtente = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nomeUtente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"; // Ottieni il valore dalla JSP\r\n");
      out.write("    console.log(\"Nome utente:\", nomeUtente); // Aggiungi questa riga per stampare nella console\r\n");
      out.write("\r\n");
      out.write("    if (!nomeUtente || nomeUtente.trim() === \"\") {\r\n");
      out.write("        window.location.href = \"userNotLoggedLogin.jsp\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Chiamata alla funzione durante il caricamento della pagina\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("    checkAuthentication();\r\n");
      out.write("    caricaListaProposte(); // Aggiunta la chiamata alla funzione caricaListaProposte\r\n");
      out.write("    \r\n");
      out.write("    // Quando la pagina è completamente caricata\r\n");
      out.write("    var contenutoBanner = $('#contenutoBanner');\r\n");
      out.write("    if (contenutoBanner.is(':empty')) {\r\n");
      out.write("        contenutoBanner.html('<p>Non stai visualizzando nessuna proposta</p>');\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <h1>Proposte progettuali</h1>\r\n");
      out.write("        <div class=\"navbar-buttons\">\r\n");
      out.write("            <a href=\"caricaProposta.jsp\" class=\"button\">Carica Proposta</a>\r\n");
      out.write("             <a href=\"logout.jsp\" class=\"button\">Logout</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- Qui puoi inserire il codice per visualizzare le proposte progettuali -->\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
